services:
  - type: web
    name: library-management
    runtime: docker
    repo: https://github.com/sukumar-cloud/LibraryManagement
    envVars:
      - key: DATABASE_URL
        value: "jdbc:mysql://your-database-host:3306/LibraryDB"
      - key: DATABASE_USER
        value: "root"
      - key: DATABASE_PASSWORD
        value: ""
