services:
  - type: web
    name: library-management
    runtime: java
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/LibraryManagementSystem.jar"
    envVars:
      - key: DATABASE_URL
        value: "jdbc:mysql://your-database-host:3306/LibraryDB"
      - key: DATABASE_USER
        value: "root"
      - key: DATABASE_PASSWORD
        value: ""
